version: '3.8'

services:

  gameapp-redis:
    platform: linux/x86_64
    image: redis:latest
    container_name: gameapp-redis
    ports:
      - "6380:6379"
    command: redis-server --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:


